/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TmApp {
    }
    interface TmBoard {
    }
    interface TmCard {
    }
    interface TmList {
    }
    interface TmModal {
        "modalTitle": string;
    }
}
export interface TmCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTmCardElement;
}
declare global {
    interface HTMLTmAppElement extends Components.TmApp, HTMLStencilElement {
    }
    var HTMLTmAppElement: {
        prototype: HTMLTmAppElement;
        new (): HTMLTmAppElement;
    };
    interface HTMLTmBoardElement extends Components.TmBoard, HTMLStencilElement {
    }
    var HTMLTmBoardElement: {
        prototype: HTMLTmBoardElement;
        new (): HTMLTmBoardElement;
    };
    interface HTMLTmCardElement extends Components.TmCard, HTMLStencilElement {
    }
    var HTMLTmCardElement: {
        prototype: HTMLTmCardElement;
        new (): HTMLTmCardElement;
    };
    interface HTMLTmListElement extends Components.TmList, HTMLStencilElement {
    }
    var HTMLTmListElement: {
        prototype: HTMLTmListElement;
        new (): HTMLTmListElement;
    };
    interface HTMLTmModalElement extends Components.TmModal, HTMLStencilElement {
    }
    var HTMLTmModalElement: {
        prototype: HTMLTmModalElement;
        new (): HTMLTmModalElement;
    };
    interface HTMLElementTagNameMap {
        "tm-app": HTMLTmAppElement;
        "tm-board": HTMLTmBoardElement;
        "tm-card": HTMLTmCardElement;
        "tm-list": HTMLTmListElement;
        "tm-modal": HTMLTmModalElement;
    }
}
declare namespace LocalJSX {
    interface TmApp {
    }
    interface TmBoard {
    }
    interface TmCard {
        "onCardClicked"?: (event: TmCardCustomEvent<any>) => void;
    }
    interface TmList {
    }
    interface TmModal {
        "modalTitle"?: string;
    }
    interface IntrinsicElements {
        "tm-app": TmApp;
        "tm-board": TmBoard;
        "tm-card": TmCard;
        "tm-list": TmList;
        "tm-modal": TmModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tm-app": LocalJSX.TmApp & JSXBase.HTMLAttributes<HTMLTmAppElement>;
            "tm-board": LocalJSX.TmBoard & JSXBase.HTMLAttributes<HTMLTmBoardElement>;
            "tm-card": LocalJSX.TmCard & JSXBase.HTMLAttributes<HTMLTmCardElement>;
            "tm-list": LocalJSX.TmList & JSXBase.HTMLAttributes<HTMLTmListElement>;
            "tm-modal": LocalJSX.TmModal & JSXBase.HTMLAttributes<HTMLTmModalElement>;
        }
    }
}
