/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TmApp {
    }
    interface TmBoard {
    }
    interface TmCard {
    }
}
declare global {
    interface HTMLTmAppElement extends Components.TmApp, HTMLStencilElement {
    }
    var HTMLTmAppElement: {
        prototype: HTMLTmAppElement;
        new (): HTMLTmAppElement;
    };
    interface HTMLTmBoardElement extends Components.TmBoard, HTMLStencilElement {
    }
    var HTMLTmBoardElement: {
        prototype: HTMLTmBoardElement;
        new (): HTMLTmBoardElement;
    };
    interface HTMLTmCardElement extends Components.TmCard, HTMLStencilElement {
    }
    var HTMLTmCardElement: {
        prototype: HTMLTmCardElement;
        new (): HTMLTmCardElement;
    };
    interface HTMLElementTagNameMap {
        "tm-app": HTMLTmAppElement;
        "tm-board": HTMLTmBoardElement;
        "tm-card": HTMLTmCardElement;
    }
}
declare namespace LocalJSX {
    interface TmApp {
    }
    interface TmBoard {
    }
    interface TmCard {
    }
    interface IntrinsicElements {
        "tm-app": TmApp;
        "tm-board": TmBoard;
        "tm-card": TmCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tm-app": LocalJSX.TmApp & JSXBase.HTMLAttributes<HTMLTmAppElement>;
            "tm-board": LocalJSX.TmBoard & JSXBase.HTMLAttributes<HTMLTmBoardElement>;
            "tm-card": LocalJSX.TmCard & JSXBase.HTMLAttributes<HTMLTmCardElement>;
        }
    }
}
